---
- name: Instalación de Docker en hosts remotos
  hosts: docker_hosts
  become: true
  tasks:
    - name: Actualizar paquetes del sistema
      apt:
        update_cache: yes

    - name: Instalar dependencias necesarias para Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Agregar clave GPG de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Agregar repositorio de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Actualizar caché después de agregar el repositorio
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Habilitar y arrancar Docker
      systemd:
        name: docker
        enabled: yes
        state: started

